version: "3"
services:
  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGODB_URI: mongodb://root:example@db:27017/
    depends_on:
      - db
    networks:
      - db-network
  db:
    image: mongo # mongo:4.4.18
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - db-network
    volumes:
      - mongodb-data:/data/db
      - ./backups:/app/backups

networks:
  db-network:
    driver: bridge

volumes:
  mongodb-data:
