version: "3"

networks:
  monitoring:

services:
#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.47.2
#    container_name: cadvisor
#    restart: unless-stopped
#    privileged: true
#    volumes:
#      - "/:/rootfs:ro"
#      - "/var/run:/var/run:ro"
#      - "/sys:/sys:ro"
#      - "/var/lib/docker/:/var/lib/docker:ro"
#      - "/dev/disk/:/dev/disk:ro"
#    networks:
#      - monitoring

#  node-exporter:
#    image: quay.io/prometheus/node-exporter:latest
#    pid: "host"
#    command:
#      - "--path.rootfs=/rootfs"
#    volumes:
#      - "/:/host:ro,rslave"
#    networks:
#      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.2
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./loki/local-config.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - monitoring

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3456:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitoring
